### ISSUE TITLE
Button Response Issue - Control4 NEEO 

### ISSUE THREAD

**Issue by asheersingh** [13mralex/c4-pyatv-remote#5]
I’m having an issue with the OK button on the Control4 NEEO with the driver. The OK button does not respond on initial click for some reason. It requires 2-3 simultaneous clicks before it will respond. All other buttons on the NEEO work flawlessly with the driver. Is this a known issue?

**Comment by 13mralex** [comment]
Changes have been published. I created a Property to allow a custom threshold (in ms) for the hold action on the OK button, with a default of 150. It was originally 100. See 13mralex/c4-pyatv-remote@732257e.
