### ISSUE TITLE
OK Button not selecting and is long pressing instead.

### ISSUE THREAD

**Issue by smarthomesydney** [13mralex/c4-pyatv-remote#6]
Have a bug of long pressing occurring on ATV4k.
No other issues.  When I select an app on the apple tv with C4 OK button.  it long presses the output and stops me from opening apps.

This occurs after a period of time and then stays.
Only fix is restarting the webserver and C4 controller.

Updated pyatv to 0.10.2 from 0.10.0 to ensure it wasn't a pyatv bug.  No change.

Any movement on adding long press option to C4 driver?
I think it may be that pyatv sees the C4 driver as requesting long press for some reason...

**Comment by 13mralex** [comment]
Addressed in #5. A custom threshold was created to help solve this.
