### ISSUE TITLE
Select button doesn't work.

### ISSUE THREAD

**Issue by bboi69** [13mralex/c4-pyatv-remote#8]
Select button on C4 doesn't work. All other IP button commands work fine.

**Comment by lilstevie** [comment]
+1 same issue here. Turned debugging on and watched the Lua Output window while sending select and this appears
`--- ReceivedFromProxy: 5001
ENTER
----PARAMS----
ROOM_ID = 56
-----ARGS-----
---
`

**Comment by snowbooch** [comment]
Think the author was going for dynamic/timed press for this button, but it didn't work for me either. Fixed it by modifying driver.lua lines 1060-1077 to simply be:

function MSP.ENTER (idBinding, strCommand, tParams, args)
	local pytvCommand = CMDS [strCommand]
	if (pytvCommand ~= nil) then
		PYATV.RemoteCommand (pytvCommand)
	end
end
